# Generated by Django 3.2.1 on 2021-05-06 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0002_rename_text_description_json'),
    ]

    operations = [
        migrations.AddField(
            model_name='description',
            name='html',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
